name: docker-build
on: push
jobs:
  deploy:
    steps:
      - name: Build image
        run: docker build . -f Dockerfile -t djinno/oci-cli:latest
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push djinno/oci-cli:latest
